name = "StockFlow"
uuid = "58c4a0e8-2944-4d18-9fa2-e17726aee9e5"
license = "MIT"
authors = ["Xiaoyan Li <xiaoyan.lyu.li@gmail.com>"]
version = "0.2.2"

[deps]
AlgebraicRewriting = "725a01d3-f174-5bbd-84e1-b9417bad95d9"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CompTime = "0fb5dd42-039a-4ca4-a1d7-89a96eae6d39"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StringManipulation = "892a3eda-7b42-436c-8928-eab12a02cf0e"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AlgebraicRewriting = "0.2.1 - 0.3.2, 0.4"
Catlab = "0.15.5 - 0.16.8, 0.16"
Combinatorics = "1.0.2"
CompTime = "0.1"
GraphViz = "0.2"
Graphs = "1.9.0"
JSON = "0.21.0"
LabelledArrays = "^1"
MLStyle = "0.4"
OrdinaryDiffEq = "6.20.0"
Plots = "1.35.3"
StaticArrays = "1.5.2"
StatsBase = "^0.33, 0.34"
StringManipulation = "0.3"
Tables = "1.7.0"
julia = "1.9 - 1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
